const API_URL = "http://localhost:8080";
const token ="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJERXF5d1IwckxYY3Z2TGVBcUQ2UXM3NFlXanlTdVh3REtURHZrSldaS1ZZIn0.eyJleHAiOjE3NzkzOTIzMzIsImlhdCI6MTc3OTM5MjAzMiwianRpIjoib25ydHJvOmQxZjM3NTNkLTYxMTEtZGE4YS0zMmVlLTZjZDg4NTU0MTcxZiIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODIwMC9yZWFsbXMvaGFiaXQtdHJhY2tlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI2ZjIxNjkxNS0yOWY2LTQ5MTctYTFkZS0wY2UxYmFkMGI3NzEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJoYWJpdC10cmFja2VyLWNsaWVudCIsInNpZCI6IjNvMy0yZmgzRHVOQ0lDMktOd3hTOVRNdCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWhhYml0LXRyYWNrZXIiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiaGFiaXQtdHJhY2tlci1jbGllbnQiOnsicm9sZXMiOlsiVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiTWF0ZXVzeiBTdMSZcGllxYQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtLnN0ZXBpZW4xNjA2QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJNYXRldXN6IiwiZmFtaWx5X25hbWUiOiJTdMSZcGllxYQiLCJlbWFpbCI6Im0uc3RlcGllbjE2MDZAZ21haWwuY29tIn0.nClWfXDhu_RN_QaiOIc_99tuyN_glwY1Aui5eE4vL_v6N4HGO-A6SMQXLty-j6z0Mb_3iZY00epNNmxKAt_7cMdTZcSUU6_GWx1hEZOrrwxiQQJeb4aeg7s1_9RXUQ90c3a_RiagzEsrsJvVrDAPUGApiuGAx4JmBl68EAKyHWna8deFmP3xzh2nCZaI4AbQlSjENSwa2vAorvbE3jDqbIj_cdO6t5lX2gSr5oNeNlh0rDUSr4cVAe7XlQLi9klZGvt6cHjdZEfrgQnuuMj0urwwxDErvviKjfe2Lcsnu2K4Xwhw4t4DtpQZfbAdtoODaGFA59_-iz6XVqRuGlwW8Q";

export async function getHabits() {
  const response = await fetch(`${API_URL}/me/habits`,{
    method: "GET",
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    throw new Error("Failed to fetch users");
  }

  return response.json();
}