const API_URL = "http://localhost:8080";
const token = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJERXF5d1IwckxYY3Z2TGVBcUQ2UXM3NFlXanlTdVh3REtURHZrSldaS1ZZIn0.eyJleHAiOjE3NzkxMjgzNTgsImlhdCI6MTc3OTEyODA1OCwianRpIjoib25ydHJvOmFjYmNmODRiLWFkZWItNDA3Mi05NDRhLTIwYzZmNDI3MWE5MSIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODIwMC9yZWFsbXMvaGFiaXQtdHJhY2tlciIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI2ZjIxNjkxNS0yOWY2LTQ5MTctYTFkZS0wY2UxYmFkMGI3NzEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJoYWJpdC10cmFja2VyLWNsaWVudCIsInNpZCI6IldnS0VXLUMxald4LU83Q0pSSExBNnJOdSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWhhYml0LXRyYWNrZXIiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiaGFiaXQtdHJhY2tlci1jbGllbnQiOnsicm9sZXMiOlsiVVNFUiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiTWF0ZXVzeiBTdMSZcGllxYQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJtLnN0ZXBpZW4xNjA2QGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJNYXRldXN6IiwiZmFtaWx5X25hbWUiOiJTdMSZcGllxYQiLCJlbWFpbCI6Im0uc3RlcGllbjE2MDZAZ21haWwuY29tIn0.OQ8sLMnNKl8JWEXlhUVOhowK-L-E1Z_C_x6NGw9SUyIbPKEVnjqXFeUcaHgVcLInFgkXYvgEjktCJWhKkLbbFPBLCrZOTDtLKPqgL2VFt-s-dfLKOvwCWLJZn4-pXZueFZtdqF8L3cVEH0vHj3bhUZecs2ZciGvH81aQNtFWfPpWTys_Qc8t-tB9rBceBsTAYKrjAZkHApplfvglN4rd0jRJsgG3AG73TikjO1TOUA3_5_8egG4-7InLqf2IPmEKlGLsEX-M0Uwk2_eujYgRruPgHooK_S14zBLxC0Orras1TPU7H4_AR4on8dt0zz7tADQOZaU_lMx3nysIP7ODqQ";

export async function getHabits() {
  const response = await fetch(`${API_URL}/me/habits`,{
    method: "GET",
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    throw new Error("Failed to fetch users");
  }

  return response.json();
}